version: '3'
services:
  php-fpm:
    image: blog
    command: php-fpm
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: base64:0uKbpXgirm30sICrGm/EQNrWmQdBV4g2SrlIVEZP8E0=
      APP_DEBUG: 1
      APP_URL: http://localhost
      LOG_CHANNEL: stderr
      LOG_STDERR_FORMATTER: Monolog\Formatter\JsonFormatter
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD:
      BROADCAST_DRIVER: log
      CACHE_DRIVER: redis
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: redis
      SESSION_LIFETIME: 120
      REDIS_HOST: redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
      MAIL_DRIVER: smtp
      MAIL_HOST: smtp.mailtrap.io
      MAIL_PORT: 2525
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_ENCRYPTION: null
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_DEFAULT_REGION: us-east-1
      AWS_BUCKET:
      PUSHER_APP_ID:
      PUSHER_APP_KEY:
      PUSHER_APP_SECRET:
      PUSHER_APP_CLUSTER: mt1
  nginx:
    image: blog
    command: /usr/sbin/nginx
    ports:
      - 30000:80
  redis:
    image: redis

